all:
  children:
    windows:
      hosts:
        sg-itdev-1:
          ansible_host: 10.10.20.150
      vars:
        ansible_user: Administrator
        ansible_password: "Stratacach3@2024"
        ansible_connection: winrm
        ansible_winrm_transport: basic
        ansible_winrm_server_cert_validation: ignore
