all:
  children:
    windows:
      hosts:
        sg-jh-1:
          ansible_host: 10.101.1.35
      vars:
        ansible_user: Administrator
        ansible_password: "StrataCach3@2025"
        ansible_connection: winrm
        ansible_winrm_transport: basic
        ansible_winrm_server_cert_validation: ignore
